name: BrainDriveInstaller
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - git=2.45.2=haa95532_2
  - icu=73.1=h6c2663c_0
  - libffi=3.4.4=hd77b12b_1
  - nodejs=20.17.0=hbad1749_0
  - openssl=3.0.17=h35632f6_0
  - python=3.11.13=h981015d_0
  - setuptools=78.1.1=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.14=h5e9d12e_1
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - altgraph==0.17.4
      - attrs==25.4.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - colorama==0.4.6
      - dulwich==0.22.6
      - gitdb==4.0.12
      - gitpython==3.1.40
      - idna==3.10
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - markupsafe==3.0.2
      - packaging==25.0
      - pefile==2023.2.7
      - pillow==11.0.0
      - pip==25.2
      - pluggy==1.6.0
      - psutil==6.1.0
      - pygments==2.19.2
      - pyinstaller==6.16.0
      - pyinstaller-hooks-contrib==2025.9
      - pytest==8.4.1
      - pytest-html==4.1.1
      - pytest-metadata==3.1.1
      - pywin32==308
      - pywin32-ctypes==0.2.3
      - referencing==0.37.0
      - requests==2.32.3
      - rpds-py==0.27.1
      - smmap==5.0.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - zipp==3.23.0
prefix: C:\Users\david\miniconda3\envs\BrainDriveInstaller
